source 'https://rubygems.org'

gem 'rake_docker', '~> 2.11'
gem 'rake_circle_ci', '~> 0.9'
gem 'rake_github', '~> 0.5'
gem 'rake_ssh', '~> 0.4'
gem 'rake_gpg', '~> 0.12'
gem 'git', '~> 1.6'
gem 'semantic', '~> 1.6'
gem 'ox', '~> 2.14.6'
